version: "3.7"

services:
  minio:
    image: quay.io/minio/minio
    restart: always 
    volumes:
      # - /opt/data:/data
      - /mnt/ssd/data:/data
      # - /mnt/ssd/data:/data
      - ./certs:/root/.minio/certs
    user: root
    environment:
      MINIO_DOMAIN: svc.t-1s.com 
      MINIO_ROOT_USER: kalpa
      MINIO_ROOT_PASSWORD: rekongpeo
      MINIO_API_CORS_ALLOW_ORIGIN: "https://svc.t-1s.com,https://svc.t-1s,http://libra:9080,http://libra:9020"
      #       MINIO_IDENTITY_OPENID_CONFIG_URL: https://dev-hsihsfug.us.auth0.com/.well-known/openid-configuration
      #       MINIO_IDENTITY_OPENID_CLIENT_ID: CoaX8mi1vB75PxpcXz5poc0XnNl7Xo3G
      # MINIO_NOTIFY_AMQP_ENABLE_one: "on"
      # MINIO_NOTIFY_AMQP_URL_one: "amqp://guest:guest@rabbitmq:5672"
      # MINIO_NOTIFY_AMQP_EXCHANGE_one: amq.direct
      # MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_one: direct
      # MINIO_NOTIFY_AMQP_ROUTING_KEY_one: s3-event
      # MINIO_NOTIFY_AMQP_MANDATORY_one: 'off'
      # MINIO_NOTIFY_AMQP_DURABLE_one: 'on'
      # MINIO_NOTIFY_AMQP_DELIVERY_MODE_one: '1'
      # MINIO_NOTIFY_AMQP_COMMENT_one: "RabbitMQ settings"
      # MINIO_NOTIFY_AMQP_QUEUE_DIR_one: '/home/events'
    ports:
      - 9000:9000
      - 9001:9001
    command:
      - server
      - /data
      - --console-address
      - "0.0.0.0:9001"
  # minio-back:
  #   image: quay.io/minio/minio
  #   restart: always 
  #   volumes:
  #     - /mnt/5tb/PhotoVault:/data
  #     - ./certs:/root/.minio/certs
  #   environment:
  #     MINIO_ROOT_USER: kalpa
  #     MINIO_ROOT_PASSWORD: rekongpeo
  #     MINIO_API_CORS_ALLOW_ORIGIN: "https://svc.t-1s.com,https://svc.t-1s,http://libra:9020,http://libra:8080"
  #     #       MINIO_IDENTITY_OPENID_CONFIG_URL: https://dev-hsihsfug.us.auth0.com/.well-known/openid-configuration
  #     #       MINIO_IDENTITY_OPENID_CLIENT_ID: CoaX8mi1vB75PxpcXz5poc0XnNl7Xo3G
  #   ports:
  #     - 9002:9002
  #     - 9003:9003
  #   command:
  #     - server
  #     - /data
  #     - --console-address
  #     - ":9003"
  #     - --address
  #     -  ":9002"
  # minio-listener:
  #   build: ./listener
  #   image: minio-flask
  #   user: root
  #   environment:
  #     TAG_SERVICE_HOST: "tag-manager"
  #     TAG_SERVICE_PORT: "8000"
  #     TAG_SERVICE_AUTH_TOKEN: "efdc792bcdaadc420d2c0ea680173b73d682c6d4"
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - /mnt/ssd/data:/data
  #     - /mnt/5tb/PhotoVault/vault:/data-out
  upload-server:
    build: ./upload-server
    image: upload-server
    environment:
      MINIO_ACCESS_KEY: kalpa
      MINIO_SECRET_KEY: rekongpeo
      MINIO_HOST: libra
      MINIO_PORT: 9000
    ports:
      - "9020:8080"
  http-server:
    image: halverneus/static-file-server:latest
    environment:
      CORS: "true"
    ports:
      - "7001:8080"
    volumes:
      - /mnt/5tb/Photovault/vault:/web
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /opt/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=chandigarh
      - POSTGRES_PASSWORD=chandigarh
  tag-manager:
    image: photo-jango
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/ajar/workspace/y_resource_app:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=chandigarh
      - POSTGRES_PASSWORD=chandigarh
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  s3-listener:
    build: ../async-tasks
    image: async-tasks
    user: root
    command: python s3_event_listener.py
    environment:
      TAG_SERVICE_HOST: "tag-manager"
      TAG_SERVICE_PORT: "8000"
      TAG_SERVICE_AUTH_TOKEN: "efdc792bcdaadc420d2c0ea680173b73d682c6d4"
      MINIO_HOST_PORT: "minio:9000"
      MINIO_USERNAME: kalpa
      MINIO_PASSWORD: rekongpeo
      AMQP_HOSTNAME: "libra"
    volumes:
      - /mnt/ssd/data:/data
      - /mnt/5tb/PhotoVault/vault:/data-out
  celery-worker:
    build: ../async-tasks
    image: async-tasks
    user: root
    command: celery -A catalog_app worker  --loglevel=INFO
    environment:
      TAG_SERVICE_HOST: "tag-manager"
      TAG_SERVICE_PORT: "8000"
      TAG_SERVICE_AUTH_TOKEN: "efdc792bcdaadc420d2c0ea680173b73d682c6d4"
      MINIO_HOST_PORT: "minio:9000"
      MINIO_USERNAME: kalpa
      MINIO_PASSWORD: rekongpeo
      AMQP_HOSTNAME: "libra"
    volumes:
      - /mnt/ssd/data:/data
      - /mnt/5tb/PhotoVault/vault:/data-out
