version: "3.7"

services:
  minio:
    image: quay.io/minio/minio
    restart: always 
    volumes:
      # - /opt/data:/data
      - /mnt/ssd/data:/data
      # - /mnt/ssd/data:/data
      - ./certs:/root/.minio/certs
    user: root
    environment:
      MINIO_DOMAIN: svc.t-1s.com 
      MINIO_ROOT_USER: kalpa
      MINIO_ROOT_PASSWORD: rekongpeo
      MINIO_API_CORS_ALLOW_ORIGIN: "https://svc.t-1s.com,https://svc.t-1s,http://libra:9080,http://libra:9020"
      #       MINIO_IDENTITY_OPENID_CONFIG_URL: https://dev-hsihsfug.us.auth0.com/.well-known/openid-configuration
      #       MINIO_IDENTITY_OPENID_CLIENT_ID: CoaX8mi1vB75PxpcXz5poc0XnNl7Xo3G
    ports:
      - 9000:9000
      - 9001:9001
    command:
      - server
      - /data
      - --console-address
      - "0.0.0.0:9001"
  minio-back:
    image: quay.io/minio/minio
    restart: always 
    volumes:
      - /mnt/5tb/PhotoVault:/data
      - ./certs:/root/.minio/certs
    environment:
      MINIO_ROOT_USER: kalpa
      MINIO_ROOT_PASSWORD: rekongpeo
      MINIO_API_CORS_ALLOW_ORIGIN: "https://svc.t-1s.com,https://svc.t-1s,http://libra:9020,http://libra:8080"
      #       MINIO_IDENTITY_OPENID_CONFIG_URL: https://dev-hsihsfug.us.auth0.com/.well-known/openid-configuration
      #       MINIO_IDENTITY_OPENID_CLIENT_ID: CoaX8mi1vB75PxpcXz5poc0XnNl7Xo3G
    ports:
      - 9002:9002
      - 9003:9003
    command:
      - server
      - /data
      - --console-address
      - ":9003"
      - --address
      -  ":9002"
  minio-listener:
    build: ./listener
    image: minio-flask
    user: root
    environment:
      TAG_SERVICE_HOST: "tag-manager"
      TAG_SERVICE_PORT: "8000"
      TAG_SERVICE_AUTH_TOKEN: "efdc792bcdaadc420d2c0ea680173b73d682c6d4"
    ports:
      - "5000:5000"
    volumes:
      - /mnt/ssd/data:/data
      - /mnt/5tb/PhotoVault/vault:/data-out
  upload-server:
    build: ./upload-server
    image: upload-server
    environment:
      MINIO_ACCESS_KEY: kalpa
      MINIO_SECRET_KEY: rekongpeo
      MINIO_HOST: libra
      MINIO_PORT: 9000
    ports:
      - "9020:8080"
  http-server:
    image: halverneus/static-file-server:latest
    environment:
      CORS: "true"
    ports:
      - "7001:8080"
    volumes:
      - /mnt/5tb/Photovault/vault:/web
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /opt/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=chandigarh
      - POSTGRES_PASSWORD=chandigarh
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_USERNAME=luckhnow
      - RABBITMQ_PASSWORD=banglore
    ports:
        - 5672:5672
        - 15672:15672
  tag-manager:
    image: photo-jango
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/ajar/workspace/y_resource_app:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=chandigarh
      - POSTGRES_PASSWORD=chandigarh
